### ISSUE TITLE
Port from static website

### ISSUE THREAD

**Issue by locks** [EmberConf/emberconf-2017#1]
- Port assets
  - [x] CSS
  - [x] Images
- Port pages
  - [ ] Homepage
  - [ ] Partials
  - [ ] Schedule (high priority)
- Port data
  - [ ] Schedule
  - [ ] Sponsors
  - [ ] Speakers
  - [ ] Faqs
  - [ ] Location and hotels
  - [ ] Previous speakers
- Port functionality
  - [ ] Page titles
  - [ ] Javascript scripts
  - [ ] Retina
  - [ ] Wufoo (low priority)
- Make it FastBoot compatible
- Add PWA functionalities
  - AppCache / ServiceWorkers

**Comment by villander** [comment]
@locks i'm making `Port pages`follow my work =D 

https://github.com/villander/emberconf-2017/tree/feature/port-pages
